### PR TITLE
fixed existence_error procedure exception when running the fruit.js n…

### PR DESCRIPTION
**Pull request by leobm**
…odejs example

The problem was, that before the async function fs.readFile was used, because when we called session.query in the 
fruit.js example, the thread.session.modules.user.rules was empty and we get an  
uncaught exception: error(existence_error(procedure, /(fruits_in, 2)), /(top_level, 0))

The qunit unit tests now run again with nodejs too.

### CODE REVIEW

**Comment by jariazavalverde** [comment]
Hi @leobm.

From next version (v0.3.0), `Session.prototype.consult` and `Session.prototype.query` methods will become asynchronous. i just updated the example. Thanks for your contribution.

**Comment by pmoura** [comment]
Regarding the asynchronous nature of consulting a file, I'm finding issues when several files are consulted in a row **and** the compilation of a file requires the previous file to already be consulted. My understanding here, and please correct me if I'm wrong, is that a consulting a file can start before the previous file consulting finish. If so, assume e.g. the the first file includes expansion rules that are expected to be used in the second file. Or that compile time optimizations of the second file can only be performed using the contents of the first file.

**Comment by jariazavalverde** [comment]
> My understanding here, and please correct me if I'm wrong, is that consulting a file can start before the previous file consulting finish.

I suppose you mean load multiple files from Prolog using, for example, the `use_module` directive or the `consult` predicate. In that case, the execution of the thread is stopped until the file has been loaded.

Currently, term and goal expansion can only be defined in the `user` module. Perhaps your problems come from this.

**Comment by pmoura** [comment]
That's what I meant. Thanks for clarifying. I will take that in account to debug the issues I'm getting.

P.S. I'm (not) currently using Tau Prolog own term-expansion mechanism.

**Comment by leobm** [comment]
> 
> 
> Hi @leobm.
> 
> From next version (v0.3.0), `Session.prototype.consult` and `Session.prototype.query` methods will become asynchronous. i just updated the example. Thanks for your contribution.

No problem. That would have been my second suggestion, to build the consult function from scratch asynchronously and return a Promise object. I only had little time, otherwise I would have extended my pull request.

**Pull request closed without merging**
