### PR TITLE
Allow user to configure random function

### PR DESCRIPTION
**Pull request by gilbert**
I've been using this successfully for a while, so here's a PR. Predicate name [inspired by SWI](https://www.swi-prolog.org/pldoc/man?predicate=set_random/1). Addresses #143

### CODE REVIEW

**Comment by pmoura** [comment]
How easy it would be to also add a predicate to get the seed?

**Comment by gilbert** [comment]
Fairly easy I imagine. Should it be called `get_random/1`?

**Comment by pmoura** [comment]
Given that you added `set_random/1`, sounds like the best choice. Thanks for looking into this.

**Comment by jariazavalverde** [comment]
JavaScript does not support setting a seed. It is necessary to implement a random number generator that allows it.

**Comment by gilbert** [comment]
Correct, one needs to assign `session.createRandom` for a seed to work. Here's how I do it in my project:

```js
const session = pl.create()
session.createRandom = createRandom

//
// Seeded random logic
//
function createRandom(seed) {
  var seed = xmur3(seed);
  return sfc32(seed(), seed(), seed(), seed());
}

// A seeded random function maker
function sfc32(a, b, c, d) {
  return function() {
    a >>>= 0; b >>>= 0; c >>>= 0; d >>>= 0;
    var t = (a + b) | 0;
    a = b ^ b >>> 9;
    b = c + (c << 3) | 0;
    c = (c << 21 | c >>> 11);
    d = d + 1 | 0;
    t = t + d | 0;
    c = c + t | 0;
    return (t >>> 0) / 4294967296;
  }
}

// A hash function
function xmur3(str) {
  for(var i = 0, h = 1779033703 ^ str.length; i < str.length; i++)
      h = Math.imul(h ^ str.charCodeAt(i), 3432918353),
      h = h << 13 | h >>> 19;
  return function() {
      h = Math.imul(h ^ h >>> 16, 2246822507);
      h = Math.imul(h ^ h >>> 13, 3266489909);
      return (h ^= h >>> 16) >>> 0;
  }
}
```

**Comment by jariazavalverde** [comment]
Thanks for your contribution @gilbert. Finally I opted to extend the prototypes of Tau Prolog to add a default generator (Mulberry32) to sessions. I found the SWI-Prolog interface a bit strange, so I relied on the GNU Prolog interface.

**Pull request closed without merging**
